// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synapse.Infrastructure.Persistence;

#nullable disable

namespace Synapse.Infrastructure.Migrations
{
    [DbContext(typeof(SynapseDbContext))]
    partial class SynapseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Synapse.Infrastructure.Entities.CommandParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<long?>("VariableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("VariableId");

                    b.ToTable("CommandParameters");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.DeviceCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("DeviceCommands");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.EndCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .HasColumnType("TEXT");

                    b.Property<string>("Item")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicOp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.Property<long>("StepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("EndConditions");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.MeasurementLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatteryChannel")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Current")
                        .HasColumnType("REAL");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<long>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSec")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Voltage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TestRunId", "BatteryChannel", "TimeSec");

                    b.ToTable("MeasurementLogs");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.Sequence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.SequenceStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("SequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SequenceId");

                    b.ToTable("SequenceSteps");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.SystemLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestRunId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.TestRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SequenceId");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<bool>("IsSync")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.Variable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.CommandParameter", b =>
                {
                    b.HasOne("Synapse.Infrastructure.Entities.DeviceCommand", "Command")
                        .WithMany("CommandParameters")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synapse.Infrastructure.Entities.Variable", "Variable")
                        .WithMany()
                        .HasForeignKey("VariableId");

                    b.Navigation("Command");

                    b.Navigation("Variable");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.DeviceCommand", b =>
                {
                    b.HasOne("Synapse.Infrastructure.Entities.SequenceStep", "Step")
                        .WithMany("DeviceCommands")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.EndCondition", b =>
                {
                    b.HasOne("Synapse.Infrastructure.Entities.SequenceStep", "Step")
                        .WithMany("EndConditions")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.MeasurementLog", b =>
                {
                    b.HasOne("Synapse.Infrastructure.Entities.TestRun", "TestRun")
                        .WithMany("MeasurementLogs")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.SequenceStep", b =>
                {
                    b.HasOne("Synapse.Infrastructure.Entities.Sequence", "Sequence")
                        .WithMany("Steps")
                        .HasForeignKey("SequenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sequence");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.SystemLog", b =>
                {
                    b.HasOne("Synapse.Infrastructure.Entities.TestRun", "TestRun")
                        .WithMany("SystemLogs")
                        .HasForeignKey("TestRunId");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.TestRun", b =>
                {
                    b.HasOne("Synapse.Infrastructure.Entities.Sequence", "Sequence")
                        .WithMany()
                        .HasForeignKey("SequenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sequence");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.DeviceCommand", b =>
                {
                    b.Navigation("CommandParameters");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.Sequence", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.SequenceStep", b =>
                {
                    b.Navigation("DeviceCommands");

                    b.Navigation("EndConditions");
                });

            modelBuilder.Entity("Synapse.Infrastructure.Entities.TestRun", b =>
                {
                    b.Navigation("MeasurementLogs");

                    b.Navigation("SystemLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
